metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
kind: Deployment
apiVersion: apps/v1
---
metadata:
  name: myapp
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
kind: Service
apiVersion: v1
